openapi: 3.0.0
info:
  title: job_offer
  version: "1.0"
servers:
- url: http://localhost:3000
paths:
  /job_offer:
    get:
      operationId: get-job_offer
      parameters:
      - description: 都道府県コード
        explode: true
        in: query
        name: prefCode
        required: true
        schema:
          type: number
        style: form
      - description: 年度
        explode: true
        in: query
        name: year
        required: true
        schema:
          type: number
        style: form
      - description: 表示内容
        explode: true
        in: query
        name: matter
        required: true
        schema:
          type: number
        style: form
      - description: 表示分類
        explode: true
        in: query
        name: class
        required: true
        schema:
          type: number
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: OK
      summary: job_offer
      tags: []
  /occupation:
    get:
      operationId: get-occupation
      parameters:
      - description: 職業大分類
        explode: true
        in: query
        name: iscoCode
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
          description: OK
      summary: occupation
      tags: []
  /total_population:
    get:
      operationId: get-total_population
      parameters:
      - description: 都道府県コード
        explode: true
        in: query
        name: prefCode
        required: true
        schema:
          type: number
        style: form
      - description: 市区町村コード
        explode: true
        in: query
        name: cityCode
        required: true
        schema:
          type: number
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
          description: OK
      summary: total_population
      tags: []
components:
  schemas:
    result_joboffer:
      example:
        finding_employment_count: 1.4658129805029452
        broadName: broadName
        valid_jobfinder: 6.027456183070403
        valid_job_offer_number: 0.8008281904610115
      properties:
        broadName:
          description: 職業大分類1
          type: string
        valid_job_offer_number:
          description: 有効求人数
          type: number
        valid_jobfinder:
          description: 有効就職者
          type: number
        finding_employment_count:
          description: 就職件数
          type: number
    inline_response_200:
      example:
        result:
          finding_employment_count: 1.4658129805029452
          broadName: broadName
          valid_jobfinder: 6.027456183070403
          valid_job_offer_number: 0.8008281904610115
        message: message
      properties:
        message:
          description: メッセージ
          type: string
        result:
          $ref: '#/components/schemas/result_joboffer'
    occupation_middle_category:
      example:
        ismcoCode: ismcoCode
        iscoCode: iscoCode
        ismcoName: ismcoName
      properties:
        iscoCode:
          description: 職業大分類コード
          type: string
        ismcoCode:
          description: 職業中分類
          type: string
        ismcoName:
          description: 職業中分類名
          type: string
    inline_response_200_1:
      example:
        result:
          ismcoCode: ismcoCode
          iscoCode: iscoCode
          ismcoName: ismcoName
        message: message
      properties:
        message:
          description: メッセージ
          type: string
        result:
          $ref: '#/components/schemas/occupation_middle_category'
    result__total_population:
      example:
        bitrh_number: 6.027456183070403
        died_number: 1.4658129805029452
        total_population: 0.8008281904610115
      properties:
        total_population:
          description: 総人口
          type: number
        bitrh_number:
          description: 出生数
          type: number
        died_number:
          description: 死亡数
          type: number
    inline_response_200_2:
      example:
        result:
          bitrh_number: 6.027456183070403
          died_number: 1.4658129805029452
          total_population: 0.8008281904610115
        message: message
      properties:
        message:
          description: メッセージ
          type: string
        result:
          $ref: '#/components/schemas/result__total_population'
